import * as React from 'react';
import Card from '@mui/material/Card';
import CardActions from '@mui/material/CardActions';
import CardContent from '@mui/material/CardContent';
import CardMedia from '@mui/material/CardMedia';
import Button from '@mui/material/Button';
import Typography from '@mui/material/Typography';
import { AboutCardProps } from './About.model';
import { Icon } from '@mui/material';
import Head from 'next/head';
import GitHubIcon from '@mui/icons-material/GitHub';

export default function AboutCard(props: AboutCardProps) {
  return (
    <div>
      <Head>
        <title>درباره‌ی ما</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />

        <link href="https://fonts.googleapis.com/css2?family=Material+Icons" rel="stylesheet" />
        <link href="https://fonts.googleapis.com/css2?family=Material+Icons+Outlined" rel="stylesheet" />
        <link href="https://fonts.googleapis.com/css2?family=Material+Icons+Round" rel="stylesheet" />
        <link href="https://fonts.googleapis.com/css2?family=Material+Icons+Sharp" rel="stylesheet" />
        <link href="https://fonts.googleapis.com/css2?family=Material+Icons+Two+Tone" rel="stylesheet" />
      </Head>
      <Card
        sx={{ maxWidth: 500, minHeight: 750 }}
        dir="rtl"
        className="flex flex-col dark:bg-custom-slate-100 bg-zinc-100 dark:text-white dark:border-custom-slate-200 border-red-600 border-2"
      >
        <CardMedia
          sx={{ minWidth: 350, minHeight: 350 }}
          component="img"
          height="140"
          image={props.cardMedia.imgLink}
          alt={props.cardMedia.imgAltText}
          className="border-red-700"
        />
        <CardContent className="flex flex-col items-start flex-grow">
          <Typography gutterBottom variant="h5" component="div">
            {props.headerTitle}
          </Typography>
          <Typography variant="body2" component={'div'} className="text-right">
            <div dangerouslySetInnerHTML={{ __html: props.description }} />
          </Typography>
        </CardContent>
        <CardActions className="flex justify-center flex-shrink-0 mb-4">
          <Button
            variant="outlined"
            className="dark:bg-custom-slate-200 dark:text-zinc-50 dark:border-blue-600 border-red-700 text-red-700 flex items-center"
            href={props.button.link}
            target="blank"
          >
            <span className="flex items-center pl-2">{props.button.icon === 'github' ? <GitHubIcon /> : <Icon>{props.button.icon}</Icon>}</span>
            <span className="flex items-center">{props.button.text}</span>
          </Button>
        </CardActions>
      </Card>
    </div>
  );
}
