import type { NextPage } from 'next';
import Head from 'next/head';
import styles from '../styles/Home.module.css';
import GeneralTable from '../components/general-table';
import { GeneralInput } from '../components/general-input';
import AppService, { Advertisement } from '../services/appService';
import CircularLoading from '../components/circularLoading';
import * as React from 'react';

const Home: NextPage = () => {
  let isLoading: boolean = true;
  let adsList: Array<Advertisement> = [];
  AppService.getJobinjaAdvertisements('node').then((response) => {
    adsList = response;
    console.log(adsList);
    isLoading = false;
  });

  return (
    <div className={styles.container}>
      <Head>
        <title>Danesh Bonyan</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="flex flex-col justify-center items-center mt-4 static overflow-hidden">
        <h1 className="font-black text-2xl mb-6">جستجوی آگهی شغلی</h1>
        <GeneralInput />
        {isLoading ? <CircularLoading /> : <GeneralTable />}
      </main>
    </div>
  );
};

export default Home;
