import type { NextPage } from 'next';
import Head from 'next/head';
import styles from '../styles/Home.module.css';
import GeneralTable from '../components/general-table';
import { GeneralInput } from '../components/general-input';
import CircularLoading from '../components/circularLoading';
import * as React from 'react';
import { useContext } from 'react';
import FetchJobinjaAdvertisementsContext, { AdvertisementList, JobinjaFetchAdProvider } from '../store/fetchJobinjaAdvertisementsContext';

const Home: NextPage = () => {
  let isLoading: boolean = true;
  let adsList: Array<AdvertisementList>;

  const jobinjaCtx: {
    advertisementList?: Array<AdvertisementList>;
    fetchJobinjaAdvertisements: (searchKeyword: string) => void;
    getJobinjaAdsList: () => Array<AdvertisementList>;
  } = useContext(FetchJobinjaAdvertisementsContext);

  function getJobinjaAdsList(): void {
    adsList = jobinjaCtx.getJobinjaAdsList();
  }

  return (
    <div className={styles.container}>
      <Head>
        <title>Danesh Bonyan</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="flex flex-col justify-center items-center mt-4 static overflow-hidden">
        <h1 className="font-black text-2xl mb-6">جستجوی آگهی شغلی</h1>
        <JobinjaFetchAdProvider>
          <GeneralInput />
          {isLoading ? <CircularLoading /> : <GeneralTable />}
        </JobinjaFetchAdProvider>
      </main>
    </div>
  );
};

export default Home;
